### ISSUE TITLE
一条非常非常小的建议

### ISSUE THREAD

**Issue by DeeChael** [MinecraftFunctionPlusPlus/MCFPP#16]
命令行中建议在 > 的后方添加一个空格，会更美观一些（虽然并不会影响什么）。
比如 Python 的命令行：
![image](https://github.com/MinecraftFunctionPlusPlus/MCFPP/assets/63186003/6eed996d-cd14-456f-97a7-8970532a3490)

**Comment by srcres258** [comment]
早已有感，但由于不知道原作者对此改进的态度故按住未表。
