### ISSUE TITLE
for循环问题

### ISSUE THREAD

**Issue by hank9999** [MinecraftFunctionPlusPlus/MCFPP#19]
在编译 `for (int i = 0; i < 5; i++)` 时会报错
将 `i++` 替换为 `i = i+1` 通过编译
可能这部分存在一些问题

```
func main() {
    for (int i = 0; i < 10; i=i+1) {
        print(i);
    }
}
```
同时 在MC 1.20.6上 上述代码运行存在异常
![image](https://github.com/MinecraftFunctionPlusPlus/MCFPP/assets/20784591/fa54a530-70f3-45ee-a919-f36d3c4814ef)
仅会打印一个1

**Comment by Alumopper** [comment]
i++和++i暂时没有做，其余已修复
