### ISSUE TITLE
while 循环问题

### ISSUE THREAD

**Issue by hank9999** [MinecraftFunctionPlusPlus/MCFPP#20]
```
func main() {
    int i = 0;
    while (i < 5) {
        print(i);
        i = i + 1;
    }
}
```
上述代码编译在MC 1.20.6中会输出一堆0
![image](https://github.com/MinecraftFunctionPlusPlus/MCFPP/assets/20784591/c5507b0b-6049-4209-9b6b-39f2c5deae92)
若使用dynamic修饰后, 执行后无响应

**Comment by Alumopper** [comment]
最近刚刚重构底层，上面的东西好多坏了还没修（

**Comment by hank9999** [comment]
> 最近刚刚重构底层，上面的东西好多坏了还没修（

辛苦了awa
