### ISSUE TITLE
一点想法：

### ISSUE THREAD

**Issue by 2b-creator** [MinecraftFunctionPlusPlus/MCFPP#7]
（1）其实fabric模组开发有一个datagen功能，能够生成诸如配方，维度，地物等数据，两者结合一下可能更好？
（2）在1.20.4以后minecraft支持宏传入，我认为这是与数据包交互的革命性的一个更新，计分板可以灵活地将其当作变量来使用，而我在clone研究仓库的时候发现有很多模拟计算机底层的操作，以后会不会考虑从1.20.4重构代码？
（3）star and watch 了这个项目，此外本人是csharper，B站私信回不去，一天后close issue

**Comment by Alumopper** [comment]
感谢建议！
避免使用宏是在性能测试以后决定的。对于宏来说，宏的占用大概和操作nbt相当，和命令的复杂程度有关。最小相当于三条记分板，例如function命令，最大可达数百倍记分板的占用，例如execute命令。而纯记分板算法的占用就平均而言仍然比宏在性能上更具有优势。
你可以看到我们在很多地方其实已经有使用宏，比如类的多态，nbt路径的拼接等等。

另外的话datagen其实我们有计划的啦！
