### ISSUE TITLE
mcfunction本身的缺陷

### ISSUE THREAD

**Issue by Maxyjof** [MinecraftFunctionPlusPlus/MCFPP#8]
我记得mcfunction本身被调用后，加上迭代的命令，总共只能1gt连续运行2w条命令吧？这个限制该如何解决呢？还是说已经不存在这个限制了？又或者说将会自动分割生成后的命令串吗？

**Comment by 2b-creator** [comment]
是2w条，但是2w是一个比较大的数字，况且我们个人认为完全可以用时间来换空间
但是这可能确实是一个需要注意的点

**Comment by Alumopper** [comment]
这个确实需要注意一下，感谢提醒的说
